smartdoor_prj/authenticate_api/urls.py
from django.urls import path
from . import views


app_name = "authenticate_api"

urlpatterns = [
    path("", views.authenticate, name=""),
]

smartdoor_prj/keymanagement/urls.py
from django.urls import path
from . import views


app_name = "keymanagement"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("update/<int:pk>", views.KeyUpdateView.as_view(), name="update_key"),
    path("delete/<int:pk>", views.KeyDeleteView.as_view(), name="delete_key"),
    path("keys/", views.keys, name="keys"),
    path("login/", views.Login.as_view(), name="login"),
    path("registration/", views.RegisterView.as_view(), name="register"),
    path("log/", views.LogView.as_view(), name="log"),
]

smartdoor_prj/smartdoor_prj/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("keymanagement.urls")),
    path("authenticate/", include("authenticate_api.urls")),
]

smartdoor_prj/keymanagement/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import CICharField


class Key(models.Model):
    """Registered NFC keys model
    """

    name = models.CharField(verbose_name="name", max_length=100)
    device = models.CharField(verbose_name="device", max_length=100)
    idm = CICharField(verbose_name="idm", max_length=16, unique=True)
    allow_423 = models.BooleanField(verbose_name="allow 423", null=True)
    allow_475 = models.BooleanField(verbose_name="allow 475", null=True)
    created_at = models.DateTimeField(verbose_name="creation time", auto_now_add=True)

    class Meta:
        verbose_name_plural = "Key model"


class LoginUser(AbstractUser):
    """LoginUser model to access keymanagement app
    """

    class Meta:
        verbose_name_plural = "Login User"

smartdoor_prj/keymanagement/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from bootstrap_modal_forms.forms import BSModalModelForm
from .models import Key


class LoginForm(AuthenticationForm):
    """Custom Login Form
    add some class and placeholder values into widget attributes
    """

    def __init__(self, request=None, *args, **kwargs) -> None:
        super().__init__(request, *args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs["placeholder"] = field.label


class KeyModelForm(BSModalModelForm):
    class Meta:
        model = Key
        fields = (
            "name",
            "device",
            "idm",
            "allow_423",
            "allow_475",
        )
        widgets = {
            "allow_423": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "allow_475": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }


class KeyRegisterForm(forms.ModelForm):
    class Meta:
        model = Key
        fields = (
            "name",
            "device",
            "idm",
            "allow_423",
            "allow_475",
        )
        widgets = {
            "allow_423": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "allow_475": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

smartdoor_prj/authenticate_api/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from keymanagement.models import Key

import json


@ensure_csrf_cookie
def authenticate(request):
    """
    Response the result of key authentication if idm request is recieved.
    """
    # For get csrf token
    if request.method == "GET":
        return JsonResponse({}, status=200)

    # For idm authentication process
    try:
        # parse requested json body
        data = json.loads(request.body)

        # check if data has idm key
        if "idm" not in data:
            return JsonResponse({"message": "has no idm key"}, status=400)

        # search for key in Key models
        querysets = Key.objects.all()
        queryset = querysets.filter(idm__iexact=data["idm"])
        if queryset:
            return JsonResponse(
                {
                    "auth": "valid",
                    "name": queryset[0].name,
                    "allow_423": queryset[0].allow_423,
                    "allow_475": queryset[0].allow_475,
                },
                status=200,
            )
        else:
            return JsonResponse({"auth": "invalid"}, status=200)
    except Exception:
        return JsonResponse({"message": "ERROR"}, status=500)

smartdoor_prj/keymanagement/views.py
import os
import logging
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, TemplateView
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from bootstrap_modal_forms.generic import BSModalUpdateView, BSModalDeleteView
from django.conf import settings
from .forms import LoginForm, KeyModelForm, KeyRegisterForm
from .models import Key

# path to root directory
BASE_DIR = getattr(settings, "BASE_DIR", None)

logger = logging.getLogger(__name__)


class Login(LoginView):
    form_class = LoginForm
    template_name = "login.html"


class HomeView(LoginRequiredMixin, ListView):
    model = Key
    context_object_name = "keys"
    template_name = "home.html"


class RegisterView(LoginRequiredMixin, CreateView):
    model = Key
    template_name = "register.html"
    form_class = KeyRegisterForm
    success_url = reverse_lazy("keymanagement:home")

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Success: Key was created.")
        logger.info(f"{form.cleaned_data['name']}'s {form.cleaned_data['device']} is registered.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Error: Key was not created.")
        return super().form_invalid(form)


class LogView(LoginRequiredMixin, TemplateView):
    template_name = "log.html"

    def get_context_data(self):
        context = super().get_context_data()
        with open(os.path.join(BASE_DIR, "logs", "django.log"), "r", encoding="utf-8") as f:
            context["log_text"] = f.read()
        return context


class KeyUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Key
    template_name = "update.html"
    form_class = KeyModelForm
    success_message = "Success: Key was updated."
    success_url = reverse_lazy("keymanagement:home")

    def form_valid(self, form):
        logger.info(f"{form.cleaned_data['name']}'s {form.cleaned_data['device']} is updated.")
        return super().form_valid(form)


class KeyDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Key
    template_name = "delete.html"
    success_message = "Success: Key was deleted."
    success_url = reverse_lazy("keymanagement:home")

    def delete(self, request, *args, **kwargs):
        object = self.get_object()
        logger.info(f"{object.name}'s {object.device} is deleted.")
        return super().delete(request, *args, **kwargs)


@login_required
def keys(request):
    data = dict()
    if request.method == "GET":
        keys = Key.objects.all()
        data["table"] = render_to_string("_keys_table.html", {"keys": keys}, request=request)
        return JsonResponse(data)

smartdoor_prj/keymanagement/templates/_keys_table.html
<table id="keys-table" class="table table-hover align-middle">
    <thead>
        <tr>
            <th class="text-center" scope="col">#</th>
            <th class="text-center" scope="col">Name</th>
            <th class="text-center" scope="col">Device</th>
            <th class="text-center" scope="col">IDm</th>
            <th class="text-center" scope="col">Allow 423 room</th>
            <th class="text-center" scope="col">Allow 475 room</th>
            <th class="text-center" scope="col">Created at</th>
            <th class="text-center" scope="col">Update / Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for key in keys %}
        <tr>
            <th class="text-center" scope="row">{{ forloop.counter }}</th>
            <td class="text-center">{{ key.name }}</td>
            <td class="text-center">{{ key.device }}</td>
            <td class="text-center">{{ key.idm }}</td>
            <td class="text-center">
                {% if key.allow_423 %}
                <i class="bi bi-check-circle-fill text-success"></i>
                {% else %}
                <i class="bi bi-x-circle-fill text-danger"></i>
                {% endif %}
            </td>
            <td class="text-center">
                {% if key.allow_475 %}
                <i class="bi bi-check-circle-fill text-success"></i>
                {% else %}
                <i class="bi bi-x-circle-fill text-danger"></i>
                {% endif %}
            </td>
            <td class="text-center">{{ key.created_at|date:"Y/m/d" }}</td>
            <td class="text-center">
                <!-- Update Key buttons -->
                <button type="button" class="update-key btn btn-sm btn-primary"
                    data-form-url="{% url 'keymanagement:update_key' key.pk %}">
                    <span class="fa-solid fa-pencil"></span>
                </button>
                <!-- Delete Key buttons -->
                <button type="button" class="delete-key btn btn-sm btn-danger"
                    data-form-url="{% url 'keymanagement:delete_key' key.pk %}">
                    <span class="fa-solid fa-trash-can"></span>
                </button>
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>

smartdoor_prj/keymanagement/templates/base.html
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- Bootstrap Icon CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Fontawesome Icons -->
    <link href="https://use.fontawesome.com/releases/v6.1.1/css/all.css" rel="stylesheet" />

    {% block head %}{% endblock %}

</head>

<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'keymanagement:home' %}">
                Smartdoor
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% block active_home %}{% endblock %}" aria-current="page"
                            href="{% url 'keymanagement:home' %}">
                            Key List
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block active_register %}{% endblock %}"
                            href="{% url 'keymanagement:register' %}">Registration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block active_log %}{% endblock %}"
                            href="{% url 'keymanagement:log' %}">Log</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block header %}{% endblock %}


    <!-- Page content-->
    {% block contents %}{% endblock %}


    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <!-- jquery core JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <!-- jquery bootstrap modal form JS -->
    <script src="{% static 'javascript/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- Core theme JS-->
    <script src="{% static 'javascript/scripts.js' %}"></script>

    <!-- extra JS -->
    {% block extrascripts %}
    {% endblock extrascripts %}
</body>

</html>

smartdoor_prj/keymanagement/templates/delete.html
{% load widget_tweaks %}

<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">Delete Key</h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <div class="modal-body">
        <p class="delete-text">Are you sure you want to delete key with
            <strong>{{ key.name }}'s {{ key.device }}</strong>?
        </p>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
    </div>

</form>

smartdoor_prj/keymanagement/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Key List
{% endblock %}

{% block active_home %}active{% endblock %}

{% block header %}
<!-- alert message -->
{% if messages %}
{% for message in messages %}
<div style="position:fixed;top:0;z-index:10000;width:100%;border-radius:0;"
    class="{{ message.tags }} alert-dismissible fade show mb-0" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endblock %}


{% block contents %}
<!-- set modal diaglog -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<!-- main -->
<div class="container">
    <div class="text-center m-5">
        <h1>List of registered NFC keys</h1>
    </div>
    {% include "_keys_table.html" %}
</div>
{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
    $(function () {
        // Update Key asynchronous button
        // message
        var asyncSuccessMessageUpdate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Key was updated.",
            "<button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$(this).remove();});",
            "<\/script>"
        ].join("");

        // modal form
        function updateKeyModalForm() {
            $(".update-key").each(function () {
                $(this).modalForm({
                    formURL: $(this).data("form-url"),
                    asyncUpdate: true,
                    asyncSettings: {
                        closeOnSubmit: true,
                        successMessage: asyncSuccessMessageUpdate,
                        dataUrl: "keys/",
                        dataElementId: "#keys-table",
                        dataKey: "table",
                        addModalFormFunction: reinstantiateModalForms
                    }
                });
            });
        }
        updateKeyModalForm();

        // Delete Key buttons - formURL is retrieved from the data of the element
        function deleteKeyModalForm() {
            $(".delete-key").each(function () {
                $(this).modalForm({
                    formURL: $(this).data("form-url"), isDeleteForm: true,
                });
            });
        }
        deleteKeyModalForm();

        function reinstantiateModalForms() {
            updateKeyModalForm();
            deleteKeyModalForm();
        }

        // Hide alert message
        $(".alert").fadeTo(2000, 500).slideUp(500, function () {
            $(this).remove();
        });
    });
</script>
{% endblock extrascripts %}

smartdoor_prj/keymanagement/templates/log.html
{% extends 'base.html' %}

{% block title %}
Log
{% endblock %}

{% block active_log %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="h3 m-4">Logs of Smartdoor system</div>
    <textarea readonly rows="30" cols="100">{{ log_text }}</textarea>
</div>


{% endblock %}

smartdoor_prj/keymanagement/templates/login.html
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login Form</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- Core theme CSS (for Login page)-->
    <link href="{% static 'css/loginstyles.css' %}" rel="stylesheet" />
    <!-- Icons -->
    <link href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" rel="stylesheet" />
</head>

<body>
    <div class="wrapper">
        <div class="card shadow-lg">
            <form action="" class="d-flex flex-column" , method="post">
                <div class="h3 text-center text-black">Login</div>

                {% csrf_token %}
                {{ form.non_field_errors }}

                <div class="d-flex align-items-center input-field my-3 mb-4">
                    <span class="far fa-user p-2"></span>
                    {{ form.username }}
                    {{ form.username.errors }}
                </div>

                <div class="d-flex align-items-center input-field mb-4">
                    <span class="fas fa-lock p-2"></span>
                    {{ form.password }}
                    <span class="fas fa-eye-slash show-pwd-toggle" id="pwd-eye"></span>
                    {{ form.password.errors }}
                </div>


                <div class="my-3 text-center">
                    <input type="submit" value="Login" class="btn btn-primary">
                    
                </div>
            </form>
        </div>
    </div>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <!-- Core theme JS-->
    <script src="{% static 'javascript/scripts.js' %}"></script>
    <!-- script for login form -->
    <script src="{% static 'javascript/login.js' %}"></script>
</body>

</html>

smartdoor_prj/keymanagement/templates/register.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}
Key Registration
{% endblock %}

{% block active_register %}active{% endblock %}

{% block contents %}

<!-- alert icon -->
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
    </symbol>
    <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
            d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
            d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
    </symbol>
</svg>

<!-- Modal window for scanning a NFC tag -->
<div class="modal fade" id="scanModal" tabindex="-1" aria-labelledby="scanModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Scan NFC tag</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- here is written in JS -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="reload">Reload</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Contents -->

<div class="container">
    <div class="h3 m-4">Register NFC key</div>
    <form method="post" id="key_form">

        {% csrf_token %}

        <div class="{% if form.non_field_errors %}is-invalid{% endif %} mb-3">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
        <div class="row mb-3">

            <!-- Allow checkbox field -->
            {% if "Allow" in field.label %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 form-check-label">
                <strong> {{ field.label_tag }}</strong>
            </label>
            <div class="col-sm-6">
                {{ field }}
            </div>

            <!-- IDm field -->
            {% elif field.label == "Idm" %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">
                <strong> {{ field.label_tag }}</strong>
            </label>
            <div class="col-sm-6">
                {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                <div class="invalid-feedback">
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}
            </div>
            <div class="col-sm-4">
                <input type="button" value="Scan" class="btn btn-success" id="nfc-scan" data-bs-toggle="modal"
                    data-bs-target="#scanModal" />
            </div>

            <!-- others field -->
            {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">
                <strong> {{ field.label_tag }}</strong>
            </label>
            <div class="col-sm-6">
                {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                <div class="invalid-feedback">
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}
            </div>

            {% endif %}
        </div>
        {% endfor %}

        <div class="offset-sm-4 col-sm-8">
            <button class="btn btn-primary" type="submit">Register</button>
        </div>
    </form>


</div>


{% endblock %}

{% block extrascripts %}
<!-- script for NFC card scan -->
<script type=module src="{% static 'javascript/nfc_scan.js' %}"></script>
{% endblock extrascripts %}

smartdoor_prj/keymanagement/templates/update.html
{% load widget_tweaks %}

<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">Update Key</h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid mb-2{% endif %}">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
        <div class="row mb-3 {% if field.errors %}invalid{% endif %}">

            <!-- Allow checkbox field -->
            {% if "Allow" in field.label %}
            <label for="{{ field.id_for_label }}" class="col-sm-3 form-check-label">
                <strong> {{ field.label_tag }}</strong>
            </label>
            <div class="col-sm-6">
                {{ field }}
            </div>

            <!-- others field -->
            {% else %}
            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">
                <strong> {{ field.label_tag }}</strong>
            </label>
            <div class="col-sm-6">
                {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                <div class="invalid-feedback">
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}
            </div>

            {% endif %}
        </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Update</button>
    </div>

</form>